version: "3.9"
services:
  db:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    ports:
      - "5432:5432"
  app:
    build:
      dockerfile: Dockerfile
    container_name: myapp
    environment:
      TELEGRAM_TOKEN: "${TELEGRAM_TOKEN}"
    ports:
      - "8080:8080"
    depends_on:
      - db